import{a as M,S as h,i as l}from"./assets/vendor-BjRz3xa9.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const a of t)if(a.type==="childList")for(const s of a.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&i(s)}).observe(document,{childList:!0,subtree:!0});function o(t){const a={};return t.integrity&&(a.integrity=t.integrity),t.referrerPolicy&&(a.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?a.credentials="include":t.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function i(t){if(t.ep)return;t.ep=!0;const a=o(t);fetch(t.href,a)}})();const P="49366539-6fd412d088ca04dcc1c9b4bd7";let E=15;const b=async(e,r)=>{try{return(await M.get("https://pixabay.com/api/",{params:{key:P,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:E,page:r}})).data}catch(o){return console.error("Error fetching images:",o),[]}};let u=new h(".gallery a",{captionsData:"alt",captionDelay:250});function S(){const e=document.querySelector(".loader");e&&(e.style.display="inline-block")}function c(){const e=document.querySelector(".loader");e&&(e.style.display="none")}const $=()=>{const e=document.querySelector(".gallery");e.innerHTML="",g()};function w(e){document.querySelector(".gallery").insertAdjacentHTML("beforeend",e.map(({webformatURL:o,largeImageURL:i,tags:t,likes:a,views:s,comments:v,downloads:x})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${i}">
          <img class="gallery-image" src="${o}" alt="${t}" loading="lazy" />
        </a>
        <div class="info">
                <p><b>Likes</b><br>${a}</p>
                <p><b>Views</b><br>${s}</p>
                <p><b>Comments</b><br>${v}</p>
                <p><b>Downloads</b><br>${x}</p>
            </div>
      </li>`).join("")),u.refresh()}function L(){u||(u=new h(".gallery a",{captionsData:"alt",captionDelay:250})),u.refresh()}function g(){const e=document.querySelector(".gallery-item");if(e){const r=e.getBoundingClientRect().height;window.scrollBy({top:r*2,left:0,behavior:"smooth"})}}function q(){const e=document.querySelector(".load-more");e&&(e.style.display="flex")}function d(){const e=document.querySelector(".load-more");e&&(e.style.display="none")}const y=document.querySelector(".form"),p=document.querySelector(".load-more");let n=1,f="",m=0;c();d();y.addEventListener("submit",async function(e){e.preventDefault();const r=y.querySelector('input[name="search-text"]').value.trim();if(!r){l.error({title:"Error",message:"Please, enter the text for search!"});return}r!==f&&(n=1,$(),g(),f=r),S();try{const o=await b(f,n);if(c(),!o||!o.hits||o.hits.length===0){l.warning({title:"Caution",message:"Sorry, there are no images matching your search query. Please try again!"}),d();return}const i=o.hits;m=o.totalHits,w(i),L();const t=Math.ceil(m/15);n>=t?d():q()}catch(o){c(),l.error({title:"Error",message:"Illegal operation."}),console.error(o)}});p&&p.addEventListener("click",async()=>{n+=1,S();try{const e=await b(f,n);if(c(),!e||!e.hits||e.hits.length===0){l.warning({title:"Caution",message:"Sorry, no more images available."}),d();return}w(e.hits),L(),g();const r=Math.ceil(m/15);n>=r?d():q()}catch(e){c(),l.error({title:"Error",message:"Error loading more images."}),console.error(e)}});
//# sourceMappingURL=index.js.map
